In [27]:
import pandas as pd

In [29]:
df = pd.read_csv(r"C:\Users\THINKPAD\Downloads\Operations_Monitoring.csv")

In [31]:
df.head()

,Month,Staff Count,Volunteers,Field Visits,Community Meetings,Donor Reports Submitted,Avg Case Response Time Days,Data Quality Score %,Monitoring Visits Completed,Operational Risk Level,Quarter
0,Jan,24,38,18,9,3,5.4,86,12,Medium,Q1
1,Feb,25,40,20,10,3,5.1,87,13,Medium,Q1
2,Mar,26,42,23,11,4,4.9,88,14,Medium,Q1
3,Apr,27,45,25,12,4,4.6,89,16,Low,Q2
4,May,28,47,27,13,4,4.4,90,17,Low,Q2

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Month                        12 non-null     object
 1   Staff Count                  12 non-null     int64
 2   Volunteers                   12 non-null     int64
 3   Field Visits                 12 non-null     int64
 4   Community Meetings           12 non-null     int64
 5   Donor Reports Submitted      12 non-null     int64
 6   Avg Case Response Time Days  12 non-null     float64
 7   Data Quality Score %         12 non-null     int64
 8   Monitoring Visits Completed  12 non-null     int64
 9   Operational Risk Level       12 non-null     object
 10  Quarter                      12 non-null     object
dtypes: float64(1), int64(7), object(3)
memory usage: 1.2+ KB

In [35]:
month_map = {
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12
}

df["Month_Number"] = df["Month"].map(month_map).astype(int)

In [37]:
df.head(12)

,Month,Staff Count,Volunteers,Field Visits,Community Meetings,Donor Reports Submitted,Avg Case Response Time Days,Data Quality Score %,Monitoring Visits Completed,Operational Risk Level,Quarter,Month_Number
0,Jan,24,38,18,9,3,5.4,86,12,Medium,Q1,1
1,Feb,25,40,20,10,3,5.1,87,13,Medium,Q1,2
2,Mar,26,42,23,11,4,4.9,88,14,Medium,Q1,3
3,Apr,27,45,25,12,4,4.6,89,16,Low,Q2,4
4,May,28,47,27,13,4,4.4,90,17,Low,Q2,5
5,Jun,29,50,30,14,5,4.2,91,18,Low,Q2,6
6,Jul,30,53,32,15,5,4.5,89,19,Medium,Q3,7
7,Aug,31,55,34,16,5,4.1,91,21,Low,Q3,8
8,Sep,32,58,37,17,6,3.9,92,22,Low,Q3,9
9,Oct,33,61,39,18,6,3.7,93,24,Low,Q4,10
10,Nov,34,63,41,19,6,3.8,92,25,Low,Q4,11
11,Dec,35,66,44,20,7,3.5,94,27,Low,Q4,12

In [39]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   month                        12 non-null     object
 1   staff_count                  12 non-null     int64
 2   volunteers                   12 non-null     int64
 3   field_visits                 12 non-null     int64
 4   community_meetings           12 non-null     int64
 5   donor_reports_submitted      12 non-null     int64
 6   avg_case_response_time_days  12 non-null     float64
 7   data_quality_score_%         12 non-null     int64
 8   monitoring_visits_completed  12 non-null     int64
 9   operational_risk_level       12 non-null     object
 10  quarter                      12 non-null     object
 11  month_number                 12 non-null     int32
dtypes: float64(1), int32(1), int64(7), object(3)
memory usage: 1.2+ KB

In [43]:
df.rename(columns={"data_quality_score_%": "data_quality_score_pct"}, inplace=True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   month                        12 non-null     object
 1   staff_count                  12 non-null     int64
 2   volunteers                   12 non-null     int64
 3   field_visits                 12 non-null     int64
 4   community_meetings           12 non-null     int64
 5   donor_reports_submitted      12 non-null     int64
 6   avg_case_response_time_days  12 non-null     float64
 7   data_quality_score_pct       12 non-null     int64
 8   monitoring_visits_completed  12 non-null     int64
 9   operational_risk_level       12 non-null     object
 10  quarter                      12 non-null     object
 11  month_number                 12 non-null     int32
dtypes: float64(1), int32(1), int64(7), object(3)
memory usage: 1.2+ KB

In [47]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\thinkpad\anaconda3\lib\site-packages (2.9.12)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy in c:\users\thinkpad\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\thinkpad\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\thinkpad\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [53]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:palvi123@localhost:5432/ngo_analytics"
)

df.to_sql(
    "operations_monitoring",
    engine,
    if_exists="replace",
    index=False
)

12