In [5]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\THINKPAD\Downloads\Program_Impact.csv")

In [7]:
df.head(10)

,Month,Region,District,Program,Target Group,Beneficiaries Reached,Female Beneficiaries,Male Beneficiaries,Children Supported,Refugees Supported,Local Vulnerable People,Training Sessions,Cases Resolved,Satisfaction Rate %,SDG Alignment,Program_ID,Quarter
0,Jan,Kigali,Gasabo,Education Support,Refugees & Vulnerable Youth,320,175,145,210,180,140,6,48,88,SDG 4 - Quality Education,PRG001,Q1
1,Jan,Eastern Province,Kirehe,Food Assistance,Refugees & Low-income Families,540,290,250,310,360,180,3,72,86,SDG 2 - Zero Hunger,PRG002,Q1
2,Jan,Southern Province,Huye,Healthcare Outreach,Women & Children,280,165,115,170,90,190,4,41,84,SDG 3 - Good Health,PRG003,Q1
3,Feb,Kigali,Nyarugenge,Livelihood Training,Youth & Women,210,130,80,55,75,135,5,36,89,SDG 8 - Decent Work,PRG004,Q1
4,Feb,Eastern Province,Bugesera,Education Support,Refugees & Vulnerable Youth,390,205,185,265,250,140,7,55,90,SDG 4 - Quality Education,PRG001,Q1
5,Feb,Western Province,Rubavu,Protection & Case Management,Refugees & At-risk Families,260,150,110,135,170,90,4,62,87,SDG 10 - Reduced Inequalities,PRG005,Q1
6,Mar,Kigali,Gasabo,Food Assistance,Refugees & Low-income Families,610,335,275,350,410,200,4,81,88,SDG 2 - Zero Hunger,PRG002,Q1
7,Mar,Eastern Province,Kirehe,Healthcare Outreach,Women & Children,330,190,140,205,160,170,5,49,85,SDG 3 - Good Health,PRG003,Q1
8,Mar,Southern Province,Huye,Livelihood Training,Youth & Women,240,145,95,70,80,160,6,42,91,SDG 8 - Decent Work,PRG004,Q1
9,Apr,Kigali,Nyarugenge,Protection & Case Management,Refugees & At-risk Families,300,170,130,145,205,95,5,73,89,SDG 10 - Reduced Inequalities,PRG005,Q2

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Month                    36 non-null     object
 1   Region                   36 non-null     object
 2   District                 36 non-null     object
 3   Program                  36 non-null     object
 4   Target Group             36 non-null     object
 5   Beneficiaries Reached    36 non-null     int64
 6   Female Beneficiaries     36 non-null     int64
 7   Male Beneficiaries       36 non-null     int64
 8   Children Supported       36 non-null     int64
 9   Refugees Supported       36 non-null     int64
 10  Local Vulnerable People  36 non-null     int64
 11  Training Sessions        36 non-null     int64
 12  Cases Resolved           36 non-null     int64
 13  Satisfaction Rate %      36 non-null     int64
 14  SDG Alignment            36 non-null     object
 15  Program_ID               36 non-null     object
 16  Quarter                  36 non-null     object
dtypes: int64(9), object(8)
memory usage: 4.9+ KB

In [11]:
df.duplicated().sum()

0

In [13]:
df["Region"].unique()
df["Program"].unique()
df["Target Group"].unique()

array(['Refugees & Vulnerable Youth', 'Refugees & Low-income Families',
       'Women & Children', 'Youth & Women', 'Refugees & At-risk Families'],
      dtype=object)

In [15]:
df["Gender_Total"] = (
    df["Female Beneficiaries"]
    + df["Male Beneficiaries"]
)

df[
    df["Gender_Total"]
    != df["Beneficiaries Reached"]
]

Empty DataFrame
Columns: [Month, Region, District, Program, Target Group, Beneficiaries Reached, Female Beneficiaries, Male Beneficiaries, Children Supported, Refugees Supported, Local Vulnerable People, Training Sessions, Cases Resolved, Satisfaction Rate %, SDG Alignment, Program_ID, Quarter, Gender_Total]
Index: []

In [17]:
df["Region"].unique()
df["District"].unique()
df["Program"].unique()
df["SDG Alignment"].unique()

array(['SDG 4 - Quality Education', 'SDG 2 - Zero Hunger',
       'SDG 3 - Good Health', 'SDG 8 - Decent Work',
       'SDG 10 - Reduced Inequalities'], dtype=object)

In [19]:
# Gender counts match total
(
    df["Female Beneficiaries"]
    + df["Male Beneficiaries"]
    == df["Beneficiaries Reached"]
).all()

True

In [21]:
# Satisfaction rate valid
df["Satisfaction Rate %"].between(0,100).all()

True

In [23]:
# No duplicate Program_ID
df["Program_ID"].duplicated().sum()

31

In [36]:
month_map = {
    "Jan": 1,
    "Feb": 2,
    "Mar": 3,
    "Apr": 4,
    "May": 5,
    "Jun": 6,
    "Jul": 7,
    "Aug": 8,
    "Sep": 9,
    "Oct": 10,
    "Nov": 11,
    "Dec": 12
}

df["Month_Number"] = df["month"].map(month_map)

In [38]:
df.head(10)

,month,region,district,program,target_group,beneficiaries_reached,female_beneficiaries,male_beneficiaries,children_supported,refugees_supported,local_vulnerable_people,training_sessions,cases_resolved,satisfaction_rate_pct,sdg_alignment,program_id,quarter,Month_Number
0,Jan,Kigali,Gasabo,Education Support,Refugees & Vulnerable Youth,320,175,145,210,180,140,6,48,88,SDG 4 - Quality Education,PRG001,Q1,1
1,Jan,Eastern Province,Kirehe,Food Assistance,Refugees & Low-income Families,540,290,250,310,360,180,3,72,86,SDG 2 - Zero Hunger,PRG002,Q1,1
2,Jan,Southern Province,Huye,Healthcare Outreach,Women & Children,280,165,115,170,90,190,4,41,84,SDG 3 - Good Health,PRG003,Q1,1
3,Feb,Kigali,Nyarugenge,Livelihood Training,Youth & Women,210,130,80,55,75,135,5,36,89,SDG 8 - Decent Work,PRG004,Q1,2
4,Feb,Eastern Province,Bugesera,Education Support,Refugees & Vulnerable Youth,390,205,185,265,250,140,7,55,90,SDG 4 - Quality Education,PRG001,Q1,2
5,Feb,Western Province,Rubavu,Protection & Case Management,Refugees & At-risk Families,260,150,110,135,170,90,4,62,87,SDG 10 - Reduced Inequalities,PRG005,Q1,2
6,Mar,Kigali,Gasabo,Food Assistance,Refugees & Low-income Families,610,335,275,350,410,200,4,81,88,SDG 2 - Zero Hunger,PRG002,Q1,3
7,Mar,Eastern Province,Kirehe,Healthcare Outreach,Women & Children,330,190,140,205,160,170,5,49,85,SDG 3 - Good Health,PRG003,Q1,3
8,Mar,Southern Province,Huye,Livelihood Training,Youth & Women,240,145,95,70,80,160,6,42,91,SDG 8 - Decent Work,PRG004,Q1,3
9,Apr,Kigali,Nyarugenge,Protection & Case Management,Refugees & At-risk Families,300,170,130,145,205,95,5,73,89,SDG 10 - Reduced Inequalities,PRG005,Q2,4

In [40]:
df["Month_Number"] = df["Month_Number"].astype(int)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month                    36 non-null     object
 1   region                   36 non-null     object
 2   district                 36 non-null     object
 3   program                  36 non-null     object
 4   target_group             36 non-null     object
 5   beneficiaries_reached    36 non-null     int64
 6   female_beneficiaries     36 non-null     int64
 7   male_beneficiaries       36 non-null     int64
 8   children_supported       36 non-null     int64
 9   refugees_supported       36 non-null     int64
 10  local_vulnerable_people  36 non-null     int64
 11  training_sessions        36 non-null     int64
 12  cases_resolved           36 non-null     int64
 13  satisfaction_rate_pct    36 non-null     int64
 14  sdg_alignment            36 non-null     object
 15  program_id               36 non-null     object
 16  quarter                  36 non-null     object
 17  Month_Number             36 non-null     int32
dtypes: int32(1), int64(9), object(8)
memory usage: 5.1+ KB

In [44]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [20]:
df.rename(columns={"satisfaction_rate_%": "satisfaction_rate_pct"}, inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month                    36 non-null     object
 1   region                   36 non-null     object
 2   district                 36 non-null     object
 3   program                  36 non-null     object
 4   target_group             36 non-null     object
 5   beneficiaries_reached    36 non-null     int64
 6   female_beneficiaries     36 non-null     int64
 7   male_beneficiaries       36 non-null     int64
 8   children_supported       36 non-null     int64
 9   refugees_supported       36 non-null     int64
 10  local_vulnerable_people  36 non-null     int64
 11  training_sessions        36 non-null     int64
 12  cases_resolved           36 non-null     int64
 13  satisfaction_rate_pct    36 non-null     int64
 14  sdg_alignment            36 non-null     object
 15  program_id               36 non-null     object
 16  quarter                  36 non-null     object
 17  month_number             36 non-null     int32
dtypes: int32(1), int64(9), object(8)
memory usage: 5.1+ KB

In [39]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\thinkpad\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\thinkpad\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\thinkpad\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\thinkpad\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [50]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:palvi123@localhost:5432/ngo_analytics"
)

df.to_sql(
    "program_impact",
    engine,
    if_exists="replace",
    index=False
)

36